# taps
tap "d12frosted/emacs-plus"
tap "caskroom/fonts"
tap "crisidev/homebrew-chunkwm"
tap "koekeishiya/formulae"

# important
brew "git"
brew "git-lfs"
brew "haskell-stack"
brew "emacs-plus", args: ["without-spacemacs-icon"]
brew "cask", args: ["ignore-dependencies"]
brew "wget"
brew "ack"
brew "ag"
brew "tree"
brew "ncdu"
brew "terminal-notifier", link: true
brew "ossp-uuid"
brew "mu"
brew "jq"
brew "fish"
brew "shellcheck"
brew "aspell"
brew "chunkwm", args: ["with-purify", "HEAD"], restart_service: :changed
brew "skhd", args: ["with-logging", "HEAD"], restart_service: :changed
brew "ffmpeg"

# scala
cask "java"
brew "sbt"
brew "scala"
brew "maven"
cask "intellij-idea"

# applications
cask "dropbox"
cask "alfred"
cask "bartender"
cask "google-chrome"
cask "firefox"
cask "gpg-suite"
cask "xquartz"
cask "font-fontawesome"
cask "font-awesome-terminal-fonts"
cask "ubersicht"
cask "mactex"
cask "cyberduck"
cask "cryptomator"
cask "slack"
cask "telegram"

# fonts
cask "font-source-code-pro"
