#!/bin/sh

# create directory for user-wide binaries
mkdir -p ~/.local/bin

if [ $(uname -s) = "Darwin" ]; then
    hash brew || {
        ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        brew update
    }

    hash wget || {
        brew install wget
    }
fi
