#+TITLE:        d12frosted environment
#+AUTHOR:       Boris Buliga <d12frosted@icloud.com>
#+EMAIL:        d12frosted@icloud.com
#+DATE:         2015-04-17
#+STARTUP:      showeverything
#+OPTIONS:      toc:nil

This repository is a dump of my dotfiles that I am trying to keep clean and organized. But I prefer to call it 'environment'.

* What's inside?

All configurations that I fear to loose by making ~rm -rf \~/~ (accidentally, for sure). Configurations are divided into 'domains' like ~emacs~, ~git~ and ~haskell~. Every domain has it's own readme file, so make sure to check them as well before running installation script.

* Dependencies

My configurations are expecting that a lot of stuff is installed on your system. As it was already told, every domain has it's own readme file where the full list of dependencies is written down.

But be aware that I am using OS X and haven't tested my configurations beyond this operating system. They should work, but I can't promise :smile:.

Note that I am planning to write some scripts that will help with dependencies checking and installation.

* Usage

Now I am using [[https://github.com/anishathalye/dotbot][dotbot]] to bootstrap my configuration, so it's very easy to install them all. Just do

#+BEGIN_SRC sh
$ ./install
#+END_SRC

* Can I use your files?

Sure you can. But should you? :D

OK, jokes aside. It will be pleasure for me, if you find something useful in my configurations. I am trying to keep things as clear as possible, but sometimes I am making very urgent changes that I forget to document and sometimes I am just lazy to do so. So in case you have questions or any problems with my configurations - just ping me. Also be aware that I am not trying to make my configurations platform independent. You should check dependencies list or installation scripts.
