#!/usr/bin/env sh

# set PATH to include Homebrew and custom scripts
export PATH=/Users/d12frosted/.config/bin:/Users/d12frosted/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin

# load scripting additions
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# config
yabai -m config layout bsp
yabai -m config top_padding    8
yabai -m config bottom_padding 8
yabai -m config left_padding   8
yabai -m config right_padding  8
yabai -m config window_gap     8

yabai -m config auto_balance off
yabai -m config split_ratio 0.5
yabai -m config window_shadow off

# opacity (requires Screen Recording permission)
yabai -m config window_opacity on
yabai -m config active_window_opacity 1.00
yabai -m config normal_window_opacity 0.90

# borders
# borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0 &

#
# setup spaces
#
for _ in $(yabai -m query --spaces | jq '.[].index | select(. > 6)'); do
  yabai -m space --destroy 7
done

function setup_space {
  local idx="$1"
  local name="$2"
  local space=
  echo "setup space $idx : $name"

  space=$(yabai -m query --spaces --space "$idx")
  if [ -z "$space" ]; then
    yabai -m space --create
  fi

  yabai -m space "$idx" --label "$name"
}

setup_space 1 emacs
setup_space 2 code
setup_space 3 web
setup_space 4 social
setup_space 5 media
setup_space 6 other

# custom application rules
yabai -m rule --add app="^Firefox$" space=3
yabai -m rule --add app="^Safari$" space=3

yabai -m rule --add app="^Discord$" space=4
yabai -m rule --add app="^Hey$" space=4
yabai -m rule --add app="^Messages$" space=4
yabai -m rule --add app="^Slack$" space=4
yabai -m rule --add app="^Telegram$" space=4

yabai -m rule --add app="^Music$" space=5
yabai -m rule --add app="^Spotify$" space=5

yabai -m rule --add app="^Transmission$" space=6
yabai -m rule --add app="^XIV on Mac$" space=6 manage=off

yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Cryptomator$" manage=off
yabai -m rule --add app="^Emacs$" title!='^$' manage=on
yabai -m rule --add app="^Finder$" title="Copy" manage=off
yabai -m rule --add app="^NIIMBOT$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app='^IntelliJ IDEA$' subrole='AXDialog' manage=off
yabai -m rule --add title="^Preferences" manage=off
yabai -m rule --add title="^Settings" manage=off
