#+TITLE: :ui theme

This module modifies Emacs' theme.

* Table of Contents :TOC:
- [[Configuration][Configuration]]
  - [[Changing theme][Changing theme]]
  - [[Changing fonts][Changing fonts]]
- [[Troubleshooting][Troubleshooting]]
  - [[Strange font symbols][Strange font symbols]]

* Configuration

** Changing theme

Although this module uses the ~leuven~ theme by default, it offers a number of
alternatives:

- *leuven:* best theme for org-mode files
- *doom-one:* nucleus-themes' flagship theme, inspired by [[https://atom.io/][Atom's]] One Dark themes
- *doom-vibrant:* a more vibrant version of doom-one
- *doom-molokai:* based on Textmate's monokai
- *doom-nova:* adapted from [[https://trevordmiller.com/projects/nova][Nova]]
- *doom-one-light:* light version of doom-one
- *doom-peacock:* based on Peacock from [[https://daylerees.github.io/][daylerees' themes]]
- *doom-tomorrow-night:* by [[https://github.com/ChrisKempson/Tomorrow-Theme][Chris Kempson]]

This can be changed by changing the ~nucleus-theme~ variable, e.g.

#+BEGIN_SRC emacs-lisp
(setq nucleus-theme 'doom-one-light)
#+END_SRC

** Changing fonts

TODO move this out of the nucleus-ui.el

nucleus/nucleus-ui.el has four relevant variables:

- ~nucleus-font~ :: the default font to use in Doom Emacs.
- ~nucleus-big-font~ :: the font to use when ~nucleus-big-font-mode~ is enabled.
- ~nucleus-variable-font~ :: the font to use when ~variable-pitch-mode~ is
  active (or where the ~variable-pitch~ face is used).
- ~nucleus-unicode-font~ :: the font used to display unicode symbols. This is
  ignored if the =:ui unicode= module is enabled.

#+BEGIN_SRC emacs-lisp
(setq nucleus-font (font-spec :family "Fira Mono" :size 12)
      nucleus-variable-pitch-font (font-spec :family "Fira Sans")
      nucleus-unicode-font (font-spec :family "DejaVu Sans Mono")
      nucleus-big-font (font-spec :family "Fira Mono" :size 19))
#+END_SRC

* Troubleshooting

** Strange font symbols

If you're seeing strange unicode symbols, this is likely because you don't have
~all-the-icons~'s font icon installed. You can install them with ~M-x
all-the-icons-install-fonts~.
