#!/usr/bin/env bash

services=$(networksetup -listnetworkserviceorder | grep 'Hardware Port')

while read line; do
  sname=$(echo "$line" | awk -F  "(, )|(: )|[)]" '{print $2}')
  sdev=$(echo "$line" | awk -F  "(, )|(: )|[)]" '{print $4}')
  # echo "Current service: $sname, $sdev, $currentservice"
  if [ -n "$sdev" ]; then
    ifconfig "$sdev" 2>/dev/null | grep 'status: active' > /dev/null 2>&1
    rc="$?"
    if [ "$rc" -eq 0 ]; then
      currentservice="$sname"
	    currentsdev="$sdev"
      break
    fi
  fi
done <<< "$(echo "$services")"

if [[ -n "$currentservice" ]]; then
  ip=$(networksetup -getinfo "$currentservice" | grep "IP address" | grep "\." | cut -c 13-)
  name=""
  if [[ "$currentservice" == "Wi-Fi" ]]; then
    name=$(networksetup -getairportnetwork "$currentsdev" | cut -c 24-)
  fi
  echo "$currentservice:::$name:::$ip"
else
  echo "none:::none:::"
fi
