#!/usr/bin/env bash

function join_by { local d=$1; shift; echo -n "$1"; shift; printf "%s" "${@/#/$d}"; }

data=(
  "$(sh ./scripts/time_script)"
  "$(sh ./scripts/date_script)"
  "$(sh ./scripts/battery_percentage_script)"
  "$(sh ./scripts/battery_charging_script)"
  "$(sh ./scripts/wifi_status_script)"
  "$(sh ./scripts/get_volume_stat)"
  "$(sh ./scripts/get_input_source)"
)
result=$(join_by '@' "${data[@]}")

echo "$result"
