#+TITLE: :ui nucleus

This module modifies Emacs' user interface.

Doom's look is loosely inspired by Atom's One Dark theme, and is largely contained in the] plugin.

+ A colorscheme inspired by Atom's One Dark theme (now available in a separate plugin: [[https://github.com/hlissner/emacs-nucleus-theme/][nucleus-themes]])
+ A custom folded-region indicator for ~hideshow~
+ "Thin bar" fringe bitmaps for ~git-gutter-fringe~
+ File-visiting buffers are slightly brighter (powered by solaire-mode)

* Table of Contents :TOC:
- [[#configuration][Configuration]]
  - [[#changing-theme][Changing theme]]
  - [[#changing-fonts][Changing fonts]]
- [[#troubleshooting][Troubleshooting]]
  - [[#strange-font-symbols][Strange font symbols]]

* Configuration
** Changing theme
Although this module uses the ~nucleus-one~ theme by default, [[https://github.com/hlissner/emacs-nucleus-theme/][nucleus-themes]] offers a number of alternatives:

+ *nucleus-one:* nucleus-themes' flagship theme, inspired by [[https://atom.io/][Atom's]] One Dark themes
+ *nucleus-vibrant:* a more vibrant version of nucleus-one
+ *nucleus-molokai:* based on Textmate's monokai
+ *nucleus-nova:* adapted from [[https://trevordmiller.com/projects/nova][Nova]]
+ *nucleus-one-light:* light version of nucleus-one
+ *nucleus-peacock:* based on Peacock from [[https://daylerees.github.io/][daylerees' themes]]
+ *nucleus-tomorrow-night:* by [[https://github.com/ChrisKempson/Tomorrow-Theme][Chris Kempson]]

This can be changed by changing the ~nucleus-theme~ variable, e.g.

#+BEGIN_SRC emacs-lisp
(setq nucleus-theme 'nucleus-molokai)
#+END_SRC

** Changing fonts
core/core-ui.el has four relevant variables:

+ ~nucleus-font~ :: the default font to use in Doom Emacs.
+ ~nucleus-big-font~ :: the font to use when ~nucleus-big-font-mode~ is enabled.
+ ~nucleus-variable-font~ :: the font to use when ~variable-pitch-mode~ is active (or where the ~variable-pitch~ face is used).
+ ~nucleus-unicode-font~ :: the font used to display unicode symbols. This is ignored if the =:ui unicode= module is enabled.

#+BEGIN_SRC emacs-lisp
(setq nucleus-font (font-spec :family "Fira Mono" :size 12)
      nucleus-variable-pitch-font (font-spec :family "Fira Sans")
      nucleus-unicode-font (font-spec :family "DejaVu Sans Mono")
      nucleus-big-font (font-spec :family "Fira Mono" :size 19))
#+END_SRC

* Troubleshooting
** Strange font symbols
If you're seeing strange unicode symbols, this is likely because you don't have ~all-the-icons~'s font icon installed. You can install them with ~M-x all-the-icons-install-fonts~.
