#!/usr/bin/env bash

function install_brew {
  hash brew || {
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    brew tap caskroom/cask
    brew update
  }
}

function install {
  install_brew
  if [ $(uname -s) != "Darwin" ]; then
    echo "Could not install package '$1' on your system."
    exit 0
  fi
  brew install $1 || brew cask install $1 || exit
}

for pkg in "$@"; do
  hash $pkg > /dev/null 2>&1 || {
    echo "Installing '$pkg'"
    install $pkg
  }
done
