#!/bin/sh

userresources=$XDG_CONFIG_HOME/xorg/xresources
usermodmap=$XDG_CONFIG_HOME/xorg/xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
  xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
  xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
  xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
  xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# I need this so much outside of Emacs.
xset r rate 180 26

# Make sure that Caps doesn't miss it's purpose.
setxkbmap -option caps:ctrl_modifier

# Automatically lock screen
xautolock &

# I rarely see my wallpapers. But when I do, I am happy.
fehbg &

# Being distracted by some obnoxious notifications is so nice.
dunst &
notify enable

# Tame the clipboard as well
clipmenud &

# Because every X needs some algebra to tame it.
d12-xmonad
