((emacs-lisp-mode . ((byte-compile-error-on-warn . t)
                     (fill-column . 70)
                     (indent-tabs-mode . nil)
                     (elisp-lint-indent-specs . ((vulpea-utils-with-file . 1)
                                                 (vulpea-utils-with-note . 1)
                                                 (org-roam-with-file . 2)
                                                 (org-with-point-at . 1)
                                                 (org-element-map . 2)
                                                 (file-templates-set . defun)
                                                 (leader-def . 0)
                                                 (dlet . 1)
                                                 (general-create-definer . 1)
                                                 (eval-with-default-dir . 1)
                                                 (bui-define-interface . 2)
                                                 (use-package . 1)
                                                 (buffer-lines-map . 1)
                                                 (buffer-lines-each . 1)
                                                 (buffer-lines-each-t . 1)
                                                 (request . defun)))))
 (org-mode . ((fill-column . 80)
              (vulpea-id-auto-targets . nil))))
