((emacs-lisp-mode . ((byte-compile-error-on-warn . t)
                     (fill-column . 70)
                     (indent-tabs-mode . nil)
                     (elisp-lint-indent-specs . ((vulpea-utils-with-file . 1)
                                                 (vulpea-utils-with-note . 1)
                                                 (org-roam-with-file . 2)
                                                 (org-element-map . 2)
                                                 (leader-def . 0)
                                                 (dlet . 1)
                                                 (general-create-definer . 1)
                                                 (eval-with-default-dir . 1)
                                                 (bui-define-interface . 2)
                                                 (use-package . 1)))))
 (org-mode . ((fill-column . 80))))
