#!/usr/bin/env bash

spacemacs=~/.spacemacs

if [ ! -e $spacemacs ]; then
  hash git || {
    echo "Can't properly bootstrap emacs since 'git' is not available on your system. Please, install it manually."
    exit 1
  }
  username=$USER
  branch="develop"
  spacemacs_link="git@github.com:$username/spacemacs.git"
  if [ $USER != "d12frosted" ]; then
    username="syl20bnr"
    branch="master"
    spacemacs_link="https://github.com/syl20bnr/spacemacs.git"
  fi
  git clone $spacemacs_link $spacemacs
  cd $spacemacs || exit
  git checkout $branch
fi

if [ $(uname -s) = "Darwin" ]; then
  if [ $(which emacs) == "/usr/bin/emacs" ]; then
    brew install emacs --HEAD --use-git-head --with-cocoa --with-gnutls --with-librsvg --with-imagemagick
  fi
fi
