#!/bin/sh

spacemacs=~/.emacs.d.spacemacs

if [ ! -e $spacemacs ]; then
    if [ $USER = "d12frosted" ]; then
        spacemacs_link="git@github.com:d12frosted/spacemacs.git"
        branch="develop"
    else
        spacemacs_link="git@github.com:syl20bnr/spacemacs.git"
        branch="master"
    fi

    git clone $spacemacs_link $spacemacs
    cd $spacemacs
    git checkout $branch
fi

if [ $(uname -s) = "Darwin" ]; then
    if [ $(which emacs) == "/usr/bin/emacs" ]
    then
        brew tap railwaycat/emacsmacport
        brew install emacs-mac --with-spacemacs-icon --with-gnutls --with-imagemagick
    fi

    hash ack || {
        brew install ack
    }

    hash ispell || {
        brew install ispell
    }
fi
