#+TITLE:        Emacs
#+AUTHOR:       Boris Buliga
#+EMAIL:        boris@d12frosted.io
#+STARTUP:      showeverything
#+OPTIONS:      toc:nil

Personal frustration and the biggest time waster in my life (comparable to video
games). Please, turn away and retain your sanity. Otherwise you might end up
tracking all your tasks, notes, thoughts and wine in Emacs.

It's impossible to run these configurations. =eru= to the rescue. If you don't
understand what I mean, it's better for you.

These configurations are highly inspired by [[https://github.com/syl20bnr/spacemacs][Spacemacs]] and [[https://github.com/hlissner/doom-emacs][Doom Emacs]].

* Install Emacs

For OS X users I recommend to install [[https://github.com/d12frosted/homebrew-emacs-plus][emacs-plus]] - GNU Emacs with some sane
defaults, available via [[https://brew.sh][brew]] package manager.

#+BEGIN_SRC
$ brew tap d12frosted/emacs-plus
$ brew install emacs-plus --HEAD
#+END_SRC

You are free™ to use whatever Emacs variant you wish to use, though I don't give
any guarantees that it will work with these configurations. In case you wish to
investigate more on this topic, please refer to [[http://emacs.stackexchange.com/a/274/5161][this answer]].

* Install configurations

/Section is under construction. Please return in -2147483648 seconds./

* Run-time dependencies

Emacs domain has lots of run-time dependencies. It's better to install them
using =eru=.

* Interesting modules

/Section is under construction. Please return in -2147483648 seconds./
