name: Emacs

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        emacs_version:
          - snapshot
    steps:
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable

      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - uses: actions/checkout@v4

      - name: Install extra dependencies
        run: |
          sudo apt-get update
          sudo apt-get install aspell fish

      - name: Install configurations
        run: ./eru.sh install emacs

      - name: Test configurations
        run: ./eru.sh test emacs
