name: Emacs

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      XDG_CONFIG_HOME: ${{ github.workspace }}

    strategy:
      matrix:
        emacs_version:
          - snapshot
    steps:
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - uses: actions/checkout@v2

      - name: Install Eldev
        run: curl -fsSL https://raw.github.com/doublep/eldev/master/webinstall/github-eldev | sh

      - name: Install configurations
        run: ./eru.sh install emacs

      - name: Test configurations
        run: ./eru.sh test emacs
